name: Bug report
description: Something isn't working, uh?
labels: [ bug ]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for filling out this issue template. If you meant to submit a suggestion, feature request, etc., please fill out the [appropriate template](https://github.com/25huizengek1/ViTune/issues/new/choose).
        Please do not submit a bug report for a network issue, unless it's an issue specific to ViTune.

        ## ⚠️ Make sure you are able to reproduce the bug with the [latest version](https://github.com/25huizengek1/ViTune/releases/latest).
        ## ⚠️ Make sure there is no issue about this bug already.

  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to reproduce the bug
      description: What did you do for the bug to show up?
      placeholder: |
        Example:
          1. Go to '...'
          2. Click on '....'
          3. Scroll down to '....'
          4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      placeholder: |
        Example:
          "This should happen..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      placeholder: |
        Example:
          "This happened instead..."
    validations:
      required: true

  - type: textarea
    id: screen-media
    attributes:
      label: Screenshots/Screen recordings
      description: |
        A picture or screen recording helps us understand the bug more.

        You can upload them directly in the text box.

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        If your bug includes a crash, please use include logs in your issue.

        To capture logs, you can use `adb logcat`, or, if you have root access on your device or installed [Shizuku](https://shizuku.rikka.app), you can use a logger of your choice, for example: [LogFox](https://github.com/F0x1d/LogFox) to record logs.
        If you can, please filter on ViTune (`app.vitune.android`/`app.vitune.android.nightly`) to unclutter the logs a bit.

        When submitting these logs here, please upload them as a file or upload them on [Pastebin](https://pastebin.com/). This way the issue ticket won't end up looking like a total mess.

  - type: input
    id: vitune-version
    attributes:
      label: ViTune version
      placeholder: |
        Example: "v1.1.4"
    validations:
      required: true

  - type: dropdown
    id: vitune-version-type
    attributes:
      label: What kind of build are you using?
      description: If you are using a debug build, please provide the exact commit hash above.
      options:
        - "Release (GitHub / F-Droid)"
        - "Nightly (F-Droid)"
        - "Debug (self-built / unsigned from source)"
    validations:
      required: true

  - type: input
    id: android-version
    attributes:
      label: Android version
      description: |
        You can find this somewhere in your Android settings.
      placeholder: |
        Example: "Android 15"
    validations:
      required: true

  - type: textarea
    id: device-info
    attributes:
      label: Device info
      description: |
        Please specify the brand/series/model of your device and the OS build, if unsure, it's probably an OEM build
      placeholder: |
        Examples:
          "I am using the Google Pixel 8 Pro, running stock Android 15."
          "I am using the Samsung Galaxy S24 Ultra, running One UI."
          "I am using the Nothing Phone 2, running Nothing OS."
    validations:
      required: true

  - type: textarea
    id: vitune-issue-description
    attributes:
      label: Upstream reproducibility
      placeholder: |
        If this issue is also reproducible with [vfsfitvnm/ViMusic](https://github.com/vfsfitvnm/ViMusic), please provide relevant information.

        If you are unsure, leave this field empty.

        Examples:
          "This issue has been reported in vfsfitvnm#xxxx"
          "In ViMusic, click on (...) and the exact same issue occurs."

  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      placeholder: |
        Additional details and attachments. If relevant, you should provide a database export here.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: This makes sure that common problems and mistakes can be avoided
      options:
        - label: I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
          required: true
        - label: I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
          required: true
        - label: This issue has not been submitted already (this is not a duplicate of another issue)
          required: true
